//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habr.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Habr.Common.Resources.ExceptionMessageResource", typeof(ExceptionMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment does not exist.
        /// </summary>
        public static string CommentDoesNotExist {
            get {
                return ResourceManager.GetString("CommentDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment is not found.
        /// </summary>
        public static string CommentIsNotFound {
            get {
                return ResourceManager.GetString("CommentIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already taken.
        /// </summary>
        public static string EmailIsAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is incorrect.
        /// </summary>
        public static string EmailIsIncorrect {
            get {
                return ResourceManager.GetString("EmailIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token was expired.
        /// </summary>
        public static string ExpiredRefreshToken {
            get {
                return ResourceManager.GetString("ExpiredRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of page must be less than or equal {0}.
        /// </summary>
        public static string IncorrectPageSize {
            get {
                return ResourceManager.GetString("IncorrectPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token is incorrect.
        /// </summary>
        public static string IncorrectRefreshToken {
            get {
                return ResourceManager.GetString("IncorrectRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post does not exist.
        /// </summary>
        public static string PostDoesNotExist {
            get {
                return ResourceManager.GetString("PostDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post is already draft.
        /// </summary>
        public static string PostIsAlreadyDraft {
            get {
                return ResourceManager.GetString("PostIsAlreadyDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post is already published.
        /// </summary>
        public static string PostIsAlreadyPublished {
            get {
                return ResourceManager.GetString("PostIsAlreadyPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post is not published.
        /// </summary>
        public static string PostIsNotPublished {
            get {
                return ResourceManager.GetString("PostIsNotPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The published post cannot be edited.
        /// </summary>
        public static string PublishedPostCannotBeEdited {
            get {
                return ResourceManager.GetString("PublishedPostCannotBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are comments attached to post.
        /// </summary>
        public static string ThereAreCommentsAttachedToPost {
            get {
                return ResourceManager.GetString("ThereAreCommentsAttachedToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete comments of other users.
        /// </summary>
        public static string UserCannotDeleteCommentsOfOtherUsers {
            get {
                return ResourceManager.GetString("UserCannotDeleteCommentsOfOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is able to delete his/her posts only.
        /// </summary>
        public static string UserIsAbleToDeleteHisHerPostsOnly {
            get {
                return ResourceManager.GetString("UserIsAbleToDeleteHisHerPostsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is able to modify his/her posts only.
        /// </summary>
        public static string UserIsAbleToModifyHisHerPostsOnly {
            get {
                return ResourceManager.GetString("UserIsAbleToModifyHisHerPostsOnly", resourceCulture);
            }
        }
    }
}
